### ISSUE TITLE
Connecting to Server delay

### ISSUE THREAD

**Issue by Grootloops33** [PABessero/Grooty-Pack#6]
Connecting to server, can take client up to 15 min to catch up. 
Appears to wait for Voicechat handshake before allowing players in.

**Comment by PABessero** [comment]
Issue does not come from:
- Voicechat
- Scaling Health

**Comment by Grootloops33** [comment]
Culprit was Project MMO tooltips in JEI;
Every item has added tooltips due to Project MMO adding requirements, JEI needs a lot of time to load all the tooltips on every item. Hence the long delay.
